name: Build All
on:
  push:
    branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the code
          uses: actions/checkout@v2
        - name: Add execution right to gradlew
          run: chmod +x ./gradlew
        - name: Build the app
          run: ./gradlew build